// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201129154042_Migration002")]
    partial class Migration002
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apelido");

                    b.Property<string>("Combate");

                    b.Property<string>("Durabilidade");

                    b.Property<string>("Editora");

                    b.Property<string>("Forca");

                    b.Property<int>("IdSuperHero");

                    b.Property<string>("IdentidadeSecreta");

                    b.Property<string>("Imagem");

                    b.Property<string>("Inteligencia");

                    b.Property<string>("NomeHero");

                    b.Property<string>("Poder");

                    b.Property<string>("Velocidade");

                    b.HasKey("Id");

                    b.ToTable("ListaFavoritos");
                });
#pragma warning restore 612, 618
        }
    }
}
